name: Commit as blackbird-bot (Quick Test)

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Log message (quick test)'
        required: true

jobs:
  commit-as-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure Git identity
        run: |
          git config user.name "blackbird-bot"
          git config user.email "blackbird-bot@users.noreply.github.com"

      - name: Append to log (existing file)
        run: |
          echo "- [$(date '+%Y-%m-%d %H:%M')] ${{ github.event.inputs.message }}" >> docs/logs/2024-03-28-bot.md

      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.BLACKBIRD_BOT_TOKEN }}
        run: |
          git add docs/logs/2024-03-28-bot.md
          git commit -m "Quick test: ${{ github.event.inputs.message }}"
          git remote set-url origin "https://${GH_TOKEN}@github.com/BlackbirdLM/blackbird-log.git"
          git push origin HEAD:main
